<?php
/**
 * Created by PhpStorm.
 * User: xky
 * Date: 2017/4/5 0005
 * Time: 11:34
 */
require './Good.php';
class Book extends Good{
    public $price;
    function __construct()
    {

    }

    public function sayHello()
    {
//        parent::sayHello(); // TODO: Change the autogenerated stub
        echo 'parent say hello';
    }
}
